WarningEliminator: Annihilator of Issues (#408)
* Fix Eslint Warnings Part 1

* Fix new Typsecript Errors

* Fix Eslint Warnings Part 2

* Fix Eslint Warnings Part 4

* Fix Infinite loop introduced by dependencies

* Update Imagemin

* Fix Eslint Warnings Part 5

* Fix Eslint Warnings Part 6

* Fix Eslint Warnings Part 7

* Fix Eslint Warnings Part 9

* Fix Eslint Warnings Part 3

* Fix Eslint Warnings Part 8

* Fix the part of the API I carelessly broke

* Fix Eslint Warnings in PreviewOttoStep.tsx

* One more fix to api.tsx

* Avoid the loop in RedeemCouponPopup

* Fix ESLint Warnings Part 10

* Refactor coupon to keep item action within event handler

* update next-pwa, removes pwa linter, fix i18n lint error

* Fix undefined.png arms image 404

* Separate router update logic

* Revert changes to AdventureUIState

* Improve useApiCall and reactive dependencies

* Pass router string instead of entire object

* reset api state when calling fetch in useApiCall, remove warning about <p> inside <div> in Mine

* Relocate otto-loading.jpg and fix 404's

* remove unused deps, remove crosschain subgraph providers, comment out test chain config and gate behind dev environment

* Move Location Images to avoid 502's

* Change the file path oops

* fix invalid contract call on yarn build for mine calls

* Fix twitter api button

* Fix a few issues with browser rendering

* fix boost not showing properly

* Remove --quiet flag from pre-commit

* Fix TypeError: add checks before mapping

* Prevent infinite loop by tracking passId update state

* Fix undefined rewards items TypeError

* Hide results button for new otters

* revert boost logic and add extra checks to remove linter warnings

* Minor fix to merge preview data with the otto after explore tx

* reduce account fetches, add TODO to try to set up refetch after backend API has caught up to the tx

* remove debug log

* Fix missing otto images in equippedbyotto

* remove oto dep on minor effect previewotto

* remove infinite loop when not logged in, clean up effects

* Lint unresolved imports

* Hide Unnecessary Scroll Bar in popups

* Prevent preview popup resizing on otto selection

* Pass Href on Checkout My Items

* Use next Router instead of Link for buttons

* simplify confirm otter logic when switching otters

* simplify confirm otter logic when switching otters

* Improve performance with passive touchstart events

* fix switching account refetch items logic, remove small debug

* <p> cannot appear as a descendant of <p>

* clean up deps

* Passive click handler, add voice

* prevent blip when sending ottters out

* fix spacing on missions switcher

* Missing useMemo deps from conflict resolution

---------

Co-authored-by: eonwarped <eonwarped@gmail.com>